piVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJRlM2bzJLSzMzY2d3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRFd01ETXdOalV5TlRSYUZ3MHpOREV3TURFd05qVTNOVFJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNpa1pJNW45VVhqeFdPd3ZOLzFEdjVDTEhhR0xkZk9jWjZHR2tVeFRSREJldmt4UkJnOGhpR2xycWsKckNsMGpNRnMzWXZVUlJ2TnpPUEp6YUROdERLNWdGK1F3eGc3WkJxeVFVc0xhcVh2MTRqT25XN3dZWWY3Wmw5agp2YVc3Ry9jdDlrTDRLdmk5a1lQTURmV1FqS2VxaHlUV3MzNXFCSjZ2MkU0MmE2OWpNVEFJMGk0MnhaMDYrNk42CkN6Sk5XY29pZDlHY2NldjZXNDZ4QXhESHZEU1pxSWcvR0htSjh3TXNHY1VJVnp0M1NUSG94bWlrZ3Y4WlhMbW8KcVpRNWQwSGJ1bm9FbllIZ0lIcFNtZFdnaEFod0F0cVJ6VDFZY3k1YmwyVDNiZVJGV21Qd2M3MGlGQytDRXdUSwphK1E1Q2taMmMxaVNuYUh6TmNUM0N4OS91S3JaQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRWXFJM2VmV1Fsa1pmSDcvOXV5V2QzR2hFekhEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQTBjcEJuSXMrTApNd3J2TDROSlYzazNFNkM5VnNheWlkcWQzU3U5ZUZjUmYyKzFEQ1FnUWpJWEtOM1ZzZFF3ODBoazBtN1hVdjk3ClhVNmlNd3c4ekNOU3RhYWVvc3pybFlqVlY2Zmgva2lPMVlOUEdMZGp4MHh5MSsxMmpXQ3VMekwrV1UxVE5saXoKaE5BdkxRMlJSazIwRmlLTlRHejg1bGJlTUtIK29oZE1HOE9IeEZydXFtUml4OUZhYnJLNmxzQmU5UHRYZVdxaAptaGJ0UGk4L0t6cHNBeXloUTBiNHRvV3FYTzMvZGNqWktQWTI2c2hHaXZ2Y3lxVU5HZGZhMFFkbjViQTk3TXNWClA5ajYydzZkbzdCQ2tuelZMenk4Zm5ZQ3lSTFA3ZDgzU21NR0NpeDJlL0NnU1JFditUMnoreXhLdXlDbHdaUHcKT3hOTW5jd3NCVjJUCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://ede50170-8770-45a7-a5a3-faecd317786f.ap-south-2.linodelke.net:443
  name: lke238246

users:
- name: lke238246-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IklLbG04czVWa2hPcTRDWHhGOTJYM0xlMGFwOW9fZGtMXzBIdzloTzJQRkkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tcTZkNWgiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZmM3MDEwNTgtMjJjYi00ZTRhLWJjYzgtMjcyMjdkNzA2Y2MzIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.oJWvEaApANYUNTGeykWj_mrViWbLmepzP-Po6kUa-nE4AjNb7VAL2nZqE7sjC56LHRgU9kcMPg2eFFugAeHELCrp7izB0Ac8Y2i8SFk5Hu-8Uw2owqKa480Cc61dAR866ldrTQ7UlhuJx4bLYk6X68mGvsd3YOnnJyYZptzaNnZogXx5umc1UtWftZFuYgtQt29ehoC0ov0IKs1uq5mDcokK9CObNaVMGem1bY934qmnywXMI92aHnN41ozjzYLtsufbpRilIYmgz9hI6hLenbs79RQw7PkWlWSJ4sw0bGi8VwcSkmjloVHWOnPdeCELM4ooF6RO2GXOaUKb2FlbSA

contexts:
- context:
    cluster: lke238246
    namespace: default
    user: lke238246-admin
  name: lke238246-ctx

current-context: lke238246-ctx
